<?php 
/* File generated by script since posh 2.0.2 */
$GLOBALS['lgMap']["myStatus"]="Mon statut";
$GLOBALS['lgMap']["addGroup"]="Ajouter un groupe";
$GLOBALS['lgMap']["Name"]="Nom";
$GLOBALS['lgMap']["contactByEmail"]="Contacter par email";
$GLOBALS['lgMap']["noArticle"]="Aucun article";
$GLOBALS['lgMap']["portalInvitationTxt"]="Vous avez &eacute;t&eacute; invit&eacute; &agrave; utiliser cette page";
$GLOBALS['lgMap']["toReadOnOtherNotebooks"]="A lire sur les autres carnets ...";
$GLOBALS['lgMap']["addOnMyNotebook"]="Ajouter ce billet dans mon carnet";
$GLOBALS['lgMap']["openLinkedArticle"]="Ouvrir l'article li&eacute;";
$GLOBALS['lgMap']["addNewPost"]="Ecrire un nouvel article";
$GLOBALS['lgMap']["comments"]="Commentaire(s)";
$GLOBALS['lgMap']["trackbacks"]="Reprise(s)";
$GLOBALS['lgMap']["addNotebookToMyPage"]="Ajouter ce carnet &agrave; mon portail";
$GLOBALS['lgMap']["changePicture"]="Modifier la photo (fichier .jpg de taille <1Mo)";
$GLOBALS['lgMap']["addAuthorInMyNetwork"]="Ajouter l'auteur dans mon r&eacute;seau";
$GLOBALS['lgMap']["theyTakeThisArticle"]="Cet article est aussi pr&eacute;sent sur les carnets suivants";
$GLOBALS['lgMap']["options"]="Options";
$GLOBALS['lgMap']["licencedFor"]="Licence accord&eacute;e &agrave;";
$GLOBALS['lgMap']["expireOn"]="Date d'expiration";
$GLOBALS['lgMap']["changeKey"]="Modifier la cl&eacute;";
$GLOBALS['lgMap']["enterClientNb"]="Num&eacute;ro client";
$GLOBALS['lgMap']["enterKey"]="Cl&eacute; d'activation";
$GLOBALS['lgMap']["publicArticle"]="Article public";
$GLOBALS['lgMap']["networkArticle"]="Juste mon r&eacute;seau";
$GLOBALS['lgMap']["privateArticle"]="Article priv&eacute;";
$GLOBALS['lgMap']["followCommentsRss"]="Suivre les commentaires";
$GLOBALS['lgMap']["GroupName"]="Carnet de groupe";
$GLOBALS['lgMap']["getInMyNotebook"]="Copier vers un de mes carnets";
$GLOBALS['lgMap']["myNotebook"]="mon carnet";
$GLOBALS['lgMap']["selectBook"]="sélectionner un carnet";
$GLOBALS['lgMap']["addtoBook"]="Ajouter au carnet";
$GLOBALS['lgMap']["privateMemberArticle"]="Réservé aux membres";
$GLOBALS['lgMap']["groupNotifSubject"]="Invitation dans un groupe";
$GLOBALS['lgMap']["groupNotifMessage"]="Bonjour,\n\n#1 vous invite dans le(s) groupe(s) suivant(s) : ";
$GLOBALS['lgMap']["bestRegards"]="Cordialement,";
$GLOBALS['lgMap']["notifEmailConfirmation"]="<b><font color='green'>%site</font> : </b>Cette valeur sera remplac&eacute;e par le nom de l'application<br /><b><font color='green'>%link</font> : </b>Cette valeur sera remplac&eacute;e par un lien vers l'application";
$GLOBALS['lgMap']["moduleInvitationTxt"]="Ajouter le widget suivant à votre portail";
$GLOBALS['lgMap']["NotebookGroup"]="Carnet de groupe";
$GLOBALS['lgMap']["groupNotifMessage2"]="\nPour accepter cette invitation, veuillez vous rendre sur #1 ,ouvrez l'onglet 'réseau' et dans vos groupes, cliquez sur 'rejoindre' pour les groupes que vous souhaitez rejoindre. Vous pourrez ensuite publier des articles et lire les articles des carnets des groupes dont vous êtes membre.";
$GLOBALS['lgMap']["log"]="logs";
$GLOBALS['lgMap']["lblFriendShareBtn5"]="Partager cet article";

?>