/* File generated by script since posh 2.0.2 */
var lang=new Array;
lang["continue"]="Continuer";
lang["server"]="Adresse du serveur MySQL :<br />(ex : localhost)";
lang["login"]="Identifiant";
lang["password"]="Mot de passe";
lang["appname"]="Nom de votre application / de votre site";
lang["adminInterface"]="Interface d'administration";
lang["menuPosition"]="Position du menu";
lang["vertical"]="Gauche/vertical";
lang["horizontal"]="Sous les onglets/horizontal";
lang["email"]="Emails";
lang["installActiveCollabSuite"]="Installer le plugin - Collaboration Suite (optionnel).";
lang["installActiveCollabSuiteDesc"]="Ce plugin ajoute des fonctionnalités collaboratives à Posh (réseau social, carnets de publication, gestion des groupes thématiques, moteur de recherche, chat, ...)";

var __lang='fr';
function lg(v_s,v_p) {
	var l_ret=lang[v_s],indef;
	if(v_p && l_ret){l_ret=l_ret.replace("$$",v_p);}
	if (l_ret==indef)l_ret=v_s;
 	return l_ret;
}