<?php 
// General
$GLOBALS['lgMap']["lblMetaSearchPrefsNbResults"]="Résultat par widget";
$GLOBALS['lgMap']["lblMetaSearchPrefsTextZoom"]="Présentation des résultats";
$GLOBALS['lgMap']["titleTextZoomOne"]="Cliquez pour afficher une seule ligne par résultat";
$GLOBALS['lgMap']["titleTextZoomTwo"]="Cliquez pour afficher seulement une partie du résultat";
$GLOBALS['lgMap']["titleTextZoomThree"]="Cliquez pour afficher l'ensemble du résultat";
$GLOBALS['lgMap']["titleTextZoomFour"]="Cliquez pour afficher l'ensemble du résultats filtré";
$GLOBALS['lgMap']["lblEnableAggregation"]="Regrouper les résultats";
$GLOBALS['lgMap']["lblDisableAggregation"]="Désactiver le regroupement";

$GLOBALS['lgMap']["lblYouHaveBeenDisconnected"]="Vous avez été déconnecté après #1 minutes d'inactivité.";
$GLOBALS['lgMap']["lblBreadcrumbsTitle"]="Mots de recherche ajoutés";
$GLOBALS['lgMap']["titleBreadcrumbsTitle"]="Cliquez pour effacer chaque mot de l'extension de requête";
$GLOBALS['lgMap']["lblHistoricalBoardTitle"]="Requêtes précédentes";
$GLOBALS['lgMap']["lblFacetsBoardTitle"]="Facettes ontologiques";
$GLOBALS['lgMap']["titleGlobalMaxResults"]="Rentrez le nombre de résultats souhaités par widget";

// Widgets
$GLOBALS['lgMap']["titleWidgetButtonAsk"]="Cliquez pour lancer une recherche local au widget";
$GLOBALS['lgMap']["labelWidgetButtonAsk"]="Rechercher";
$GLOBALS['lgMap']["titleWidgetTypeSearch"]="Rentrez les mots de votre recherche";
$GLOBALS['lgMap']["titleWidgetMaxResults"]="Rentrez le nombre de résultats souhaités";
$GLOBALS['lgMap']["lblCollectingResults"]="Réception de résultats de cette source";
$GLOBALS['lgMap']["lblGotNoResults"]="Aucun résultat n'a été trouvé";
$GLOBALS['lgMap']["lblOneResultFound"]="1 résultat trouvé";
$GLOBALS['lgMap']["lblNumberOfResultsFound"]="#1 résultats trouvés";
$GLOBALS['lgMap']["lblContextMenuMorphoFilterX1"]="Cliquez pour choisir un filtre morphologique";
$GLOBALS['lgMap']["lblContextMenuAddToBreadcrumb"]="Hover pour ajouter le mot aux breadcrumbs";
$GLOBALS['lgMap']["lblContextMenuRestrictToOntoTermX1"]="Cliquez pour voire les occurrences concernents ce mot";
$GLOBALS['lgMap']["lblContextMenuExploreOntoFacets"]="Cliquez pour explorer le mot dans les facettes ontologiques";
$GLOBALS['lgMap']["lblContextMenuRestrictToOntoTerm1"]="Util. F1";
$GLOBALS['lgMap']["lblContextMenuRestrictToOntoTerm2"]="Util. F2";
$GLOBALS['lgMap']["lblContextMenuRestrictToOntoTerm3"]="Util. F3";
$GLOBALS['lgMap']["lblActionsOnWord"]="Cliquez à droite pour voir les actions possibles";
$GLOBALS['lgMap']["titleOpenResult"]="Cliquez pour ouvrir le résultat dans un nouvel onglet";

// Widgetprefs
$GLOBALS['lgMap']["lblPrefsOpen"]="Cliquez pour regler les préférences de ce widget";
$GLOBALS['lgMap']["lblPrefsLoadFailed"]="Le chargement des préférence a echoué";
$GLOBALS['lgMap']["lblPrefsClose"]="Fermer";
$GLOBALS['lgMap']["lblPrefsCloseTitle"]="Cliquez pour fermer la fenêtre de préférences";
$GLOBALS['lgMap']["lblPrefsSave"]="Enregistrer";
$GLOBALS['lgMap']["lblPrefsSaveTitle"]="Cliquez pour enregistrer ces préférences pour les prochaines requêtes avenc ce widget";
$GLOBALS['lgMap']["lblPrefsSavedOk"]="Enregistré!";


//Bibsonomy
$GLOBALS['lgMap']["titleBibsonomyResourceType"]="Choisissez le type de resource qui vous intéresse";
$GLOBALS['lgMap']["titleBibsonomyUserRestrict"]="Rentrez un nom d'utilisateur pour limiter la recherche";

// Ontological facets
$GLOBALS['lgMap']["titleOntoFacetsSearch"]="Rentrez un terme pour explorer ses facettes ontologiques";
$GLOBALS['lgMap']["lblOntoExploreFacets"]="Cliquez pour explorer les facettes ontologiques";
$GLOBALS['lgMap']['lblOntoFacetsBroader'] = "Termes plus généraux";
$GLOBALS['lgMap']['lblOntoFacetsNarrower'] = "Termes plus spécifiques";
$GLOBALS['lgMap']['lblOntoFacetsRelated'] = "Termes rélationnés";
$GLOBALS['lgMap']['titleOntoFacetsBroader'] = "Cliquez pour montrer/cacher les termes plus généraux trouvés par #1";
$GLOBALS['lgMap']['titleOntoFacetsNarrower'] = "Cliquez pour montrer/cacher les termes plus spécifiques trouvés par #1";
$GLOBALS['lgMap']['titleOntoFacetsRelated'] = "Cliquez pour montrer/cacher les termes rélationnés trouvés par #1";

//TagCloud
$GLOBALS['lgMap']["lblTagCloudeReloadTitle"]="Cliquez pour rafraîchir l'historique";
$GLOBALS['lgMap']["lblTagCloudeEraseTitle"]="Cliquez pour effacer vos requêtes de l'historique";
$GLOBALS['lgMap']["lblHistoricalRecency"]="Historique";

// Survista
$GLOBALS['lgMap']["lblSkosBroaderProperty"]="est plus général que";
$GLOBALS['lgMap']["lblSkosNarrowerProperty"]="est moins général que";
$GLOBALS['lgMap']["lblSkosRelatedProperty"]="est lié à";

// Zen-filter
$GLOBALS['lgMap']["titleLaunchZenFilter"]="Cliquez pour filtrer";

// Widget Morelikethis
$GLOBALS['lgMap']["titleLaunchWidgetMLT"]="Cliquez pour afficher des resultats proches a celui ci";

// Other originally in POSH
/* File generated by script since posh 2.0.2 */
$GLOBALS['lgMap']["datasourcenotavailable"]="Cette source des données paraît indisponible pour le moment. Essayez encore un fois plus tard, svp.";
$GLOBALS['lgMap']["lblRefresh"]="Rafraîchir";
$GLOBALS['lgMap']["lblHello"]="Bonjour";
$GLOBALS['lgMap']["lblBtnSend"]="Envoyer";
$GLOBALS['lgMap']["lblNoModule"]="<i>Aucun widget</i>";
$GLOBALS['lgMap']["lblSave"]="Enregistrer";
$GLOBALS['lgMap']["lblMissingPassword"]="Mot de passe oubli&eacute;";
$GLOBALS['lgMap']["lblNewPassword"]="Nouveau mot de passe";
$GLOBALS['lgMap']["lblUpload"]="T&eacute;l&eacute;charger";
$GLOBALS['lgMap']["title"]="Titre";
$GLOBALS['lgMap']["continue"]="Suite";
$GLOBALS['lgMap']["defaultIcon"]="Icone par d&eacute;faut";
$GLOBALS['lgMap']["defineDirectory"]="Proposer son emplacement dans l'annuaire de widgets";
$GLOBALS['lgMap']["addRssFeed"]="R&eacute;f&eacute;rencer un flux RSS";
$GLOBALS['lgMap']["addRssFeedToDirectory"]="Ajouter un flux RSS dans l'annuaire de widgets";
$GLOBALS['lgMap']["createYourModules"]="Cr&eacute;er vos widgets";
$GLOBALS['lgMap']["createRssFeed"]="Cr&eacute;er et proposer un widget d'information et son flux RSS";
$GLOBALS['lgMap']["createExpertModule"]="Cr&eacute;er un widget Avanc&eacute;";
$GLOBALS['lgMap']["keywords"]="Tags";
$GLOBALS['lgMap']["update"]="Mettre &agrave; jour";
$GLOBALS['lgMap']["suppress"]="Supprimer";
$GLOBALS['lgMap']["feedDetail"]="D&eacute;tail de ce widget";
$GLOBALS['lgMap']["addArticle"]="Ajouter un nouvel article";
$GLOBALS['lgMap']["add"]="Ajouter";
$GLOBALS['lgMap']["cancel"]="Annuler";
$GLOBALS['lgMap']["description"]="Description";
$GLOBALS['lgMap']["modify"]="Modifier";
$GLOBALS['lgMap']["useThisPortal"]="Utiliser cette page";
$GLOBALS['lgMap']["addThisModuleInMyPage"]="Ajouter ce widget dans ma page";
$GLOBALS['lgMap']["modificationApplied"]="Les modifications ont bien été appliquées !";
$GLOBALS['lgMap']["passwordModified"]="Votre mot de passe est modifié !";
$GLOBALS['lgMap']["hello"]="Bonjour";
$GLOBALS['lgMap']["close"]="Fermer";
$GLOBALS['lgMap']["returnHome"]="Retour vers la page d'accueil";
$GLOBALS['lgMap']["missingModule"]="Le widget est manquant !!";
$GLOBALS['lgMap']["addModAlreadyAccount"]="Avez-vous d&eacute;j&agrave; une page, dans lequel vous voulez ajouter ce widget";
$GLOBALS['lgMap']["no"]="Non";
$GLOBALS['lgMap']["yes"]="Oui";
$GLOBALS['lgMap']["addModuleOnPortal"]="ajouter ce widget sur ma page";
$GLOBALS['lgMap']["createPortalFromKw"]="cr&eacute;er un nouveau portail &agrave; partir de mes tags (s&eacute;par&eacute;s par des virgules)";
$GLOBALS['lgMap']["exampleKw"]="ex: cinema, google, gastronomie, emploi, produit:ipod nano, ...";
$GLOBALS['lgMap']["createMyPortal"]="Cr&eacute;er cette page";
$GLOBALS['lgMap']["email"]="Email";
$GLOBALS['lgMap']["yourEmail"]="Votre email";
$GLOBALS['lgMap']["password"]="Mot de Passe";
$GLOBALS['lgMap']["passwordMissing"]="Mot de passe oubli&eacute;";
$GLOBALS['lgMap']["passwordNotTyped"]="Vous n'avez pas entr&eacute; votre mot de passe";
$GLOBALS['lgMap']["addTheModule"]="Ajouter le widget";
$GLOBALS['lgMap']["yourAccount"]="Votre compte";
$GLOBALS['lgMap']["addModSelectPage"]="S&eacute;lectionner la page dans laquelle vous voulez ajouter ce widget";
$GLOBALS['lgMap']["yourArchivedArticles"]="Vos articles enregistr&eacute;s";
$GLOBALS['lgMap']["startNavigatorOnCurrent"]="D&eacute;marrer Internet Explorer ou Firefox sur cette page";
$GLOBALS['lgMap']["modifyAccount"]="Modifier mon compte";
$GLOBALS['lgMap']["disconnect"]="D&eacute;connexion";
$GLOBALS['lgMap']["yourAreRegistredNewsletter"]="Vous &ecirc;tes maintenant inscrit &agrave; la newsletter";
$GLOBALS['lgMap']["newsletterDesc"]="Soyez avertis des nouveaux services et des nouvelles fonctionnalit&eacute;s en vous inscrivant la newsletter";
$GLOBALS['lgMap']["ok"]="Ok";
$GLOBALS['lgMap']["newsletterUnsuscribe"]="Vous d&eacute;sinscrire de la newsletter";
$GLOBALS['lgMap']["newsletterUnsubscribeBody"]="Bonjour\n\n\n\nNous avons bien pris en compte votre demande de désinscription de la newsletter PORTANEO:\n\n\n\nA bientôt,\n\n\n\n.";
$GLOBALS['lgMap']["yourRequestIsTreated"]="Votre demande a bien été traitée";
$GLOBALS['lgMap']["valid"]="Valider";
$GLOBALS['lgMap']["emailSent"]="Email(s) envoy&eacute;(s) !";
$GLOBALS['lgMap']["messageSent"]="Message(s) interne(s) envoy&eacute;(s) !";
$GLOBALS['lgMap']["notMember"]="Vous n'&ecirc;tes pas encore inscrit sur ce site";
$GLOBALS['lgMap']["alreadyMember"]="Cet utilisateur est déjà inscrit";
$GLOBALS['lgMap']["incorrectLogin"]="Utilisateur inconnu ou mot de passe incorrect !";
$GLOBALS['lgMap']["userNotValidated"]="Utilisateur non validé. Veuillez le valider grace aux indications de l'email reçu dans votre boite email !";
$GLOBALS['lgMap']["technicalIssue"]="Problème technique. Veuillez réessayer ulterieurement !";
$GLOBALS['lgMap']["remarkTakeInAccount"]="Votre remarque ou demande a bien été envoyée";
$GLOBALS['lgMap']["yourRequest"]="Votre demande";
$GLOBALS['lgMap']["yourRequestBody"]="Bonjour\n\n\n\nNous avons bien pris en compte votre demande:\n\n#1\n\n\n\nNous y apportons une réponse dans les plus brefs délais.\n\n\n\nCordialement,\n\n\n\n.";
$GLOBALS['lgMap']["erroneousEmail"]="Email faux. N'oubliez pas la partie finale du mail (ex: @provider.com)";
$GLOBALS['lgMap']["subscribeConfirmation"]="Confirmation d'inscription à ";
$GLOBALS['lgMap']["subscribeConfirmationBody"]="Bonjour\n\n\n\nVotre inscription a bien été prise en compte. Nous vous rappelons vos informations d'identification:\n\n#1\n\n\n\nCes informations vous permettront d'accéder à votre compte.\n\n\n\nMerci et à bientôt";
$GLOBALS['lgMap']["invitesYouOnMsg"]=" vous invite &agrave; essayer ce #1widget</A>.";
$GLOBALS['lgMap']["proposedSharing"]="Votre page a été proposée à la publication";
$GLOBALS['lgMap']["invitesYouOnPortalMsg"]=" vous invite &agrave; utiliser #1cette page</A>";
$GLOBALS['lgMap']["sentBy"]="Envoy&eacute; par ";
$GLOBALS['lgMap']["yourModules"]="Mes widgets";
$GLOBALS['lgMap']["youHaveNoModVal"]="Vous n'avez aucun widget actif";
$GLOBALS['lgMap']["youHaveXModVal"]="Vous avez inscrit #1 widget(s)";
$GLOBALS['lgMap']["youHaveNoModWait"]="Vous n'avez aucun widget en attente de validation";
$GLOBALS['lgMap']["youHaveXModWait"]="Vous avez #1 widget(s) en attente de validation";
$GLOBALS['lgMap']["createOrManageMods"]="Cr&eacute;ez / g&eacute;rez vos propres widgets";
$GLOBALS['lgMap']["showPageWithModule"]="Non, cr&eacute;er un compte";
$GLOBALS['lgMap']["connection"]="Connexion";
$GLOBALS['lgMap']["automaticConnection"]="M&eacute;moriser";
$GLOBALS['lgMap']["yourActiveModules"]="Widgets actifs";
$GLOBALS['lgMap']["yourWaitingModules"]="Widgets en attente de validation";
$GLOBALS['lgMap']["createFromRssFeed"]="Cr&eacute;er un widget &agrave; partir d'un flux RSS existant";
$GLOBALS['lgMap']["youHaveJustCreatedThisModule"]="Vous venez de cr&eacute;er un widget. Veuillez attendre qu'il soit valid&eacute; pour l'utiliser et le partager !";
$GLOBALS['lgMap']["login"]="Identifiant";
$GLOBALS['lgMap']["passwordMissingTxt"]="Vous ne vous souvenez pas de votre mot de passe ?<BR />Indiquez nous ci-dessous votre email, nous vous enverrons un nouveau mot de passe<BR /> &agrave; cette adresse";
$GLOBALS['lgMap']["passwordMissingBody"]="Bonjour\n\n\n\nSuite à votre demande, nous avons réinitialisé votre mot de passe. Voici vos identifiants :\n\n#1\n\n\n\n\n\nCordialement,\n\n\n\n.";
$GLOBALS['lgMap']["moduleTemporalyUnavailable"]="En raison de probl&egrave;mes techniques ce widget est temporairement indisponible. Vous pouvez le supprimer de votre page, nous vous pr&eacute;viendrons d&egrave;s qu'il sera &agrave; nouveau accessible. Veuillez nous excuser pour ce d&eacute;sagr&eacute;ment.";
$GLOBALS['lgMap']["moduleNotAvailableAnymore"]="En raison de probl&egrave;mes techniques ce widget n'est plus disponible au catalogue. Nous sommes d&eacute;sol&eacute;s pour ce d&eacute;sagr&eacute;ment.";
$GLOBALS['lgMap']["moddefEquivalentModules"]="Voici une liste des services &eacute;quivalents :";
$GLOBALS['lgMap']["pleaseConnectToYourPortals"]="Veuillez vous connecter";
$GLOBALS['lgMap']["yourMessage"]="Votre message";
$GLOBALS['lgMap']["by"]="Par";
$GLOBALS['lgMap']["send"]="Envoyer";
$GLOBALS['lgMap']["searchResultsFor"]="R&eacute;sultats pour la recherche";
$GLOBALS['lgMap']["nextPage"]="Page suivante";
$GLOBALS['lgMap']["previousPage"]="Page pr&eacute;c&eacute;dente";
$GLOBALS['lgMap']["modules"]="Widgets";
$GLOBALS['lgMap']["notebookUpdated"]="Votre carnet a &eacute;t&eacute; mis &agrave; jour !";
$GLOBALS['lgMap']["moduleInvitationTxt"]="Ajouter le widget suivant à votre portail";
$GLOBALS['lgMap']["lblMandatoryFields"]="Les champs munis du signe * sont obligatoires";
$GLOBALS['lgMap']["submit"]="Enregistrer";
$GLOBALS['lgMap']["hours"]="heure(s)";
$GLOBALS['lgMap']["pleaseTryLater"]="Pour vous reconnecter, réessayez dans";
$GLOBALS['lgMap']["tooManyTry"]="Trop de connexions erronées";
$GLOBALS['lgMap']["confirmPassword"]="Confirmer le mot de passe";
$GLOBALS['lgMap']["createNewRSS"]="Cr&eacute;er un nouveau flux RSS";
$GLOBALS['lgMap']["advancedSearch"]="Recherche avancée";
$GLOBALS['lgMap']["fileTooBig"]="La taille du fichier est trop grande";
$GLOBALS['lgMap']["extensionNotAllowed"]="Ce type de fichier n'est pas admis";
$GLOBALS['lgMap']["uploadNotSuccessful"]="Ce téléchargement n'a pas fonctionné";
$GLOBALS['lgMap']["nextStep"]="Etape suivante";
$GLOBALS['lgMap']["unsubscribeMessage"]="Vous avez été désinscrit";
$GLOBALS['lgMap']["accountUnsubscribe"]="Pour vous désincrire ";
$GLOBALS['lgMap']["lblClickHere"]="cliquez ici";
$GLOBALS['lgMap']["newCommentsOnNotebook"]="Vous avez des nouveaux commentaires";
$GLOBALS['lgMap']["commentsOnFollowingArticles"]="Vous avez de nouveaux commentaires sur les articles suivants :";
$GLOBALS['lgMap']["lblZenRecomputeFacettesUsing"]="Cliquez pour recalculer les facettes ontoglogiques sur";

function lg(){
	$str=func_get_arg(0);
	$ret=(!empty($GLOBALS['lgMap'][$str]))?$GLOBALS['lgMap'][$str]:$str;
	for ($i=1;$i<func_num_args();$i++){$arg=func_get_arg($i);$ret=str_replace("#".$i,$arg,$ret);}
	return $ret;
}
?>