<?php
#############################################
#
# HEG Geneve
# Fabio Ricci Tel. +41(76)5281961
#
# RODIN COLORS SKIN "first"
# 8.8.2010
#
#############################################


$COLOR_PAGE_BACKGROUND = "#FFF9EA";
$COLOR_PAGE_BACKGROUND2 = "rgba(238,232,201,1)"; // same as #eee8C9;
$COLOR_PAGE_BACKGROUND2_TRANSLUCID = "rgba(238,232,201,0.75)";
$COLOR_PAGE_BACKGROUND3 = "rgba(170,165,150,1)"; // same as #aaa596;
$COLOR_PAGE_BACKGROUND3_TRANSLUCID = "rgba(170,165,150,0.75)";
$COLOR_WARNINGS							="#aa3333"; 
$COLOR_BLACK								="black";
$COLOR_FACET_NORMAL					="#888";
$COLOR_PAGE_WHITE						="white";
$COLOR_PAGE_INPUT						="white";
$COLOR_MENUTITLEBAR					="#EAA400";
$COLOR_MENUCONTENT					="white";
$COLOR_METASEARCHTEXT_IN_BC	="#0066CC";
$COLOR_NEARLYUNVISIBLETEXT	="#eee8C9";
$COLOR_LITTLEVISIBLETEXT		="#bbb8c9";
$COLOR_MOREVISIBLETEXT			="#777794";
$COLOR_BC_RESULT_TEXT				="black";
$COLOR_BC_ONTO_TEXT					="#990000";
$COLOR_BC_ZEN_TEXT					="#442200";
$COLOR_BC_SURVISTA_TEXT			="#002244";
$COLOR_SUPERVISIBLETEXT			="#333333";
$COLOR_BORDERLINE						= "#eee";
$COLOR_TAB_UNSELECTED				="#DAAF85";
$COLOR_MENU_BAR							="#";

$COLOR_WIDGET_TITLEBAR			=$COLOR_PAGE_BACKGROUND;
$COLOR_WIDGET_BORDERLINE		=$COLOR_BORDERLINE;
$COLOR_WIDGET_BG						=$COLOR_PAGE_WHITE;
$COLOR_WIDGET_RESULT_BG			=$COLOR_WIDGET_BG;
$COLOR_WIDGET_UNMARKRESULT	=$COLOR_WIDGET_RESULT_BG;
$COLOR_WIDGET_RESULT_SEPARATION	='#999';
$COLOR_WIDGET_MARKRESULT		='#eeeeff';
$COLOR_WIDGET_MARKRESULT2		='#ccccff';

$COLOR1_TAGCLOUD				="#444";
$COLOR2_TAGCLOUD				="#888";

$COLOR_ZEN_FILTER_BOX = "#555";
$COLOR_ZEN_FILTER_TERMS = "#ddd";
$COLOR_ZEN_FILTER_BUTTONS = "#777";
$COLOR_ZEN_FILTER_HOVER = "#aaa";

$COLOR_WIDGET_PREFS_BG = "lightgray";
$COLOR_WIDGET_PREFS_BG_BORDER = "gray";
$COLOR_BG_HIGHLIGHT = "#5f5";

$RODIN_COLORS = 1;
#############################################
?>