<?php
#############################################
#
# HEG Geneve
# Fabio Ricci Tel. +41(76)5281961
#
# RODIN COLORS SKIN "fresh"
# 8.8.2010
#
#############################################


$COLOR_PAGE_BACKGROUND = "#afa";
$COLOR_PAGE_BACKGROUND2 = "#7f7";
$COLOR_PAGE_BACKGROUND2bis = "#dFd9cA";
$COLOR_PAGE_BACKGROUND2_TRANSLUCID = "#3a3";
$COLOR_PAGE_BACKGROUND3 = "#171";
$COLOR_PAGE_BACKGROUND3_TRANSLUCID = "rgba(170,165,150,0.75)";
$COLOR_PAGE_BACKGROUND4 = "#5c5";
$RODIN_UPPERAREA_BGCOLOR = $COLOR_PAGE_BACKGROUND4;

$COLOR_WARNINGS							="#aa3333"; 
$COLOR_ONTOFACET_TEMPOFF		="lightgray";
$COLOR_BLACK								="black";
$COLOR_FACET_NORMAL					="#888";
$COLOR_PAGE_WHITE						="white";
$COLOR_PAGE_INPUT						="white";
$COLOR_MENUTITLEBAR					="#7777bb";
$COLOR_MENUCONTENT					="white";
$COLOR_METASEARCHTEXT_IN_BC	="#0066CC";
$COLOR_NEARLYUNVISIBLETEXT	="#eee8C9";
$COLOR_LITTLEVISIBLETEXT		="white";
$COLOR_MOREVISIBLETEXT			="#777794";
$COLOR_MOREVISIBLETEXT			="gray"; //FRI 12.7.2013 after intro upper area (darker)
$COLOR_BC_RESULT_TEXT				="black";
$COLOR_BC_ONTO_TEXT					="#990000";
$COLOR_BC_ZEN_TEXT					="#442200";
$COLOR_BC_SURVISTA_TEXT			="#002244";
$COLOR_SUPERVISIBLETEXT			="#333333";
$COLOR_BORDERLINE						= "#eee";
$COLOR_TAB_UNSELECTED				="#DAAF85";
$COLOR_MENU_BAR							="#";

$COLOR_WIDGET_TITLEBAR			=$COLOR_PAGE_BACKGROUND;
$COLOR_WIDGET_BORDERLINE		=$COLOR_BORDERLINE;
$COLOR_WIDGET_BG						=$COLOR_PAGE_WHITE;
$COLOR_WIDGET_RESULT_BG			=$COLOR_WIDGET_BG;
$COLOR_WIDGET_UNMARKRESULT	=$COLOR_WIDGET_RESULT_BG;
$COLOR_WIDGET_RESULT_SEPARATION	='#999';
$COLOR_WIDGET_MARKRESULT		='#eeeeff';
$COLOR_WIDGET_MARKRESULT2		='#ccccff';
$COLOR_BACKGROUND_WIDGET_CACHED = '#F7F7FF';
$COLOR_BACKGROUND_UVIEW_LOD = '#a3a3FF';
$RDFIZING_AGGVIEW_BGCOLOR		= '#dddddd';
$COLOR_WIDGET_HEADER = $COLOR_PAGE_BACKGROUND4;

$COLOR1_TAGCLOUD				="#444";
$COLOR2_TAGCLOUD				="#888";

$COLOR_ZEN_FILTER_BOX = "#555";
$COLOR_ZEN_FILTER_TERMS = "#ddd";
$COLOR_ZEN_FILTER_BUTTONS = "#777";
$COLOR_ZEN_FILTER_HOVER = "#aaa";

$COLOR_WIDGET_PREFS_BG = "lightgray";
$COLOR_WIDGET_PREFS_BG_BORDER = "gray";
$COLOR_BG_HIGHLIGHT = "#5f5";

#RDF PART:
$TRIPLES_COLOR_BG='#FFeeee';
$TRIPLEPAGE_RODIN_COLOR_BG_DARKER='#BBFFBB';
$TRIPLEPAGE_RODINE_COLOR_BG_DARKER='#FFBBBB';
$TRIPLEPAGE_RODINA_COLOR_BG_DARKER='#FFFFFF';
$TRIPLEPAGE_RODIN_COLOR_BG_LIGHTER='#CCFFCC';
$TRIPLEPAGE_RODINE_COLOR_BG_LIGHTER='#FFCCCC';
$TRIPLEPAGE_RODINA_COLOR_BG_LIGHTER='#EEEEFF';
$TRIPLEPAGE_RODIN_COLOR_BG_WHITE='#F0FCF0';
$TRIPLEPAGE_RODINE_COLOR_BG_WHITE='#FCF0F0';
$TRIPLEPAGE_RODINA_COLOR_BG_WHITE='#FFF';
$TRIPLEPAGE_COLOR_NSLINK='#5555AA';



$RODIN_COLORS = 1;
#############################################
?>