<?php
#############################################
#
# HEG Geneve
# Fabio Ricci Tel. +41(76)5281961
#
# RODIN COLORS SKIN "fresh"
# 8.8.2010
#
#############################################


$COLOR_PAGE_BACKGROUND			="#FFF9EA";
$COLOR_PAGE_BACKGROUND2			="#eee8C9"; // etwas dunkler
$COLOR_PAGE_WHITE				="white";
$COLOR_WARNINGS							="#aa3333"; 
$COLOR_PAGE_INPUT				="white";
$COLOR_MENUTITLEBAR				="#0E679A"; //original
$COLOR_MENUCONTENT				=$COLOR_PAGE_BACKGROUND;
$COLOR_NEARLYUNVISIBLETEXT		="#eee8C9";
$COLOR_LITTLEVISIBLETEXT		="#bbb8c9";
$COLOR_MOREVISIBLETEXT			="#777794";
$COLOR_SUPERVISIBLETEXT			="#333333";
$COLOR_BORDERLINE				=$COLOR_PAGE_BACKGROUND;
$COLOR_TAB_UNSELECTED			="#DAAF85";
$COLOR_MENU_BAR					="#";

$COLOR_WIDGET_TITLEBAR			=$COLOR_PAGE_BACKGROUND;
$COLOR_WIDGET_BORDERLINE		=$COLOR_PAGE_BACKGROUND;
$COLOR_WIDGET_BG				=$COLOR_PAGE_BACKGROUND;
$COLOR_WIDGET_RESULT_BG			=$COLOR_PAGE_BACKGROUND;
$COLOR_WIDGET_MARKRESULT		="#eeeeff";
$COLOR_WIDGET_UNMARKRESULT		=$COLOR_PAGE_BACKGROUND;
$COLOR_WIDGET_RESULT_SEPARATION	='#999';
$COLOR_WIDGET_MARKRESULT2		="ccccff";

$COLOR1_TAGCLOUD				="red";
$COLOR2_TAGCLOUD				="green";

$COLOR_ZEN_FILTER_BOX = "#555";
$COLOR_ZEN_FILTER_TERMS = $COLOR_PAGE_BACKGROUND;
$COLOR_ZEN_FILTER_BUTTONS = "#eee";
$COLOR_ZEN_FILTER_HOVER = $COLOR_PAGE_BACKGROUND2;

$COLOR_WIDGET_PREFS_BG = "lightgray";
$COLOR_WIDGET_PREFS_BG_BORDER = "gray";

$RODIN_COLORS=1;
#############################################
?>