/* File generated by script since posh 2.0.2 */
var lang=new Array;
lang["continue"]="Continuar";
lang["server"]="Servidor MySQL :<br />(ej : localhost)";
lang["login"]="Login";
lang["password"]="Password";
lang["appname"]="Nombre de tu aplicaci&oacute;n / portal web";
lang["adminInterface"]="Interfaz de administraci&oacute;n";
lang["menuPosition"]="Posici&oacute;n del Men&uacute;";
lang["vertical"]="Izquierda/vertical";
lang["horizontal"]="Bajo las pesta&ntilde;as/horizontal";
lang["email"]="Emails";
lang["installActiveCollabSuite"]="Install the Plugin - Collaboration Suite (optional).";
lang["installActiveCollabSuiteDesc"]="This plugin adds collaboratives functionalities to Posh (social network, books of publication, management of the thematic groups, search engine, chat,...)";

var __lang='es';
function lg(v_s,v_p) {
	var l_ret=lang[v_s],indef;
	if(v_p && l_ret){l_ret=l_ret.replace("$$",v_p);}
	if (l_ret==indef)l_ret=v_s;
 	return l_ret;
}