<?php 
// General
$GLOBALS['lgMap']["lblMetaSearchPrefsNbResults"]="Results per widget";
$GLOBALS['lgMap']["lblMetaSearchPrefsTextZoom"]="Presentation of results";
$GLOBALS['lgMap']["titleTextZoomOne"]="Click to show results in compact view";
$GLOBALS['lgMap']["titleTextZoomTwo"]="Click to show results in normal view";
$GLOBALS['lgMap']["titleTextZoomThree"]="Click to show results in detailed view";
$GLOBALS['lgMap']["titleTextZoomFour"]="Click to show results filtered in current view";
$GLOBALS['lgMap']["lblEnableAggregation"]="Aggregated result view";
$GLOBALS['lgMap']["lblDisableAggregation"]="Disable aggregated result view";
$GLOBALS['lgMap']["lblYouHaveBeenDisconnected"]="You have been disconnected after #1 minutes of inactivity.";
$GLOBALS['lgMap']["lblBreadcrumbsTitle"]="Additional search terms";
$GLOBALS['lgMap']["titleBreadcrumbsTitle"]="Click to remove all additional search terms"; 
$GLOBALS['lgMap']["lblHistoricalBoardTitle"]="Past Searches";
$GLOBALS['lgMap']["lblFacetsBoardTitle"]="Ontological Facets";
$GLOBALS['lgMap']["titleGlobalMaxResults"]="Enter the wished number of results per widget";

// Widgets
$GLOBALS['lgMap']["titleWidgetButtonAsk"]="Click to submit a local widget search";
$GLOBALS['lgMap']["labelWidgetButtonAsk"]="Search";
$GLOBALS['lgMap']["titleWidgetTypeSearch"]="Please, type your search here";
$GLOBALS['lgMap']["titleWidgetMaxResults"]="Please, type the number of results you wish to display";
$GLOBALS['lgMap']["lblCollectingResults"]="Collecting results from this source";
$GLOBALS['lgMap']["lblGotNoResults"]="Sorry, no results have been found";
$GLOBALS['lgMap']["lblOneResultFound"]="1 result found";
$GLOBALS['lgMap']["lblNumberOfResultsFound"]="#1 results found";
$GLOBALS['lgMap']["lblContextMenuAddToBreadcrumb"]="Click to add the word to breadcrumbs";
$GLOBALS['lgMap']["lblContextMenuMorphoFilterX1"]="Hover to choose one of the morphological filters";
$GLOBALS['lgMap']["lblContextMenuRestrictToOntoTermX1"]="Click to filter occurrencies of this word in results";
$GLOBALS['lgMap']["lblContextMenuRestrictToOntoTerm1"]="direct";
$GLOBALS['lgMap']["lblContextMenuRestrictToOntoTerm2"]="skos D";
$GLOBALS['lgMap']["lblContextMenuRestrictToOntoTerm3"]="F3?";
$GLOBALS['lgMap']["lblContextMenuExploreOntoFacets"]="Click to explore the word in ontological facets";
$GLOBALS['lgMap']["lblActionsOnWord"]="Right-click to see available actions";
$GLOBALS['lgMap']["titleOpenResult"]="Click to open result information in new tab";

// Widgetprefs
$GLOBALS['lgMap']["lblPrefsOpen"]="Click to set search preferences";
$GLOBALS['lgMap']["lblPrefsLoadFailed"]="Loading search preferences has failed";
$GLOBALS['lgMap']["lblPrefsClose"]="Close";
$GLOBALS['lgMap']["lblPrefsCloseTitle"]="Click to close search preference section";
$GLOBALS['lgMap']["lblPrefsSave"]="Save";
$GLOBALS['lgMap']["lblPrefsSaveTitle"]="Click to save search preferences for all the next RODIN searches with this widget";
$GLOBALS['lgMap']["lblPrefsSavedOk"]="Saved!";

//Bibsonomy
$GLOBALS['lgMap']["titleBibsonomyResourceType"]="Click to select the type of resource you are interested in";
$GLOBALS['lgMap']["titleBibsonomyUserRestrict"]="Enter a username to restrict the search";

//Ontological facets
$GLOBALS['lgMap']["titleOntoFacetsSearch"]="Fill in a term to explore its ontological facets";
$GLOBALS['lgMap']["lblOntoExploreFacets"]="Click to explore the ontological facets of your query";
$GLOBALS['lgMap']['lblOntoFacetsBroader'] = "More general terms";
$GLOBALS['lgMap']['lblOntoFacetsNarrower'] = "More specific terms";
$GLOBALS['lgMap']['lblOntoFacetsRelated'] = "Related terms";
$GLOBALS['lgMap']['titleOntoFacetsBroader'] = "Show/hide more general terms of #1";
$GLOBALS['lgMap']['titleOntoFacetsNarrower'] = "Show/hide more specific terms of #1";
$GLOBALS['lgMap']['titleOntoFacetsRelated'] = "Show/hide related terms of #1";

//TagCloud
$GLOBALS['lgMap']["lblTagCloudeReloadTitle"]="Click to refresh the words in the history";
$GLOBALS['lgMap']["lblTagCloudeEraseTitle"]="Click to erase the words in the history";
$GLOBALS['lgMap']["lblHistoricalRecency"]="History";

//Survista
$GLOBALS['lgMap']["lblSkosBroaderProperty"]="is more general than";
$GLOBALS['lgMap']["lblSkosNarrowerProperty"]="is less general than";
$GLOBALS['lgMap']["lblSkosRelatedProperty"]="is related to";

//Zen-filter
$GLOBALS['lgMap']["titleLaunchZenFilter"]="Click to filter and keep only some interesting terms";

// Widget Morelikethis
$GLOBALS['lgMap']["titleLaunchWidgetMLT"]="Click to display widgets documents ranked with respect to this result";

//Other originally in POSH
/* File generated by script since posh 2.0.2 */
$GLOBALS['lgMap']["datasourcenotavailable"]="Sorry, this data source seems to be currently unavailable. Please try again later.";
$GLOBALS['lgMap']["lblRefresh"]="Refresh";
$GLOBALS['lgMap']["lblHello"]="Hello";
$GLOBALS['lgMap']["lblBtnSend"]="Send";
$GLOBALS['lgMap']["lblNoModule"]="<i>No widget</i>";
$GLOBALS['lgMap']["lblSave"]="Save";
$GLOBALS['lgMap']["lblMissingPassword"]="Forgot your password";
$GLOBALS['lgMap']["lblNewPassword"]="New password";
$GLOBALS['lgMap']["lblUpload"]="Upload";
$GLOBALS['lgMap']["title"]="Title";
$GLOBALS['lgMap']["continue"]="Continue";
$GLOBALS['lgMap']["defaultIcon"]="Default icon";
$GLOBALS['lgMap']["defineDirectory"]="Propose its directory place";
$GLOBALS['lgMap']["addRssFeed"]="Add an existing RSS feed";
$GLOBALS['lgMap']["addRssFeedToDirectory"]="Add an RSS feed to the widgets library";
$GLOBALS['lgMap']["createYourModules"]="Create your own widgets";
$GLOBALS['lgMap']["createRssFeed"]="Create an RSS feed";
$GLOBALS['lgMap']["createExpertModule"]="Create an advanced widget";
$GLOBALS['lgMap']["keywords"]="Tags";
$GLOBALS['lgMap']["update"]="Update";
$GLOBALS['lgMap']["close"]="Close";
$GLOBALS['lgMap']["suppress"]="Remove";
$GLOBALS['lgMap']["feedDetail"]="Widget details";
$GLOBALS['lgMap']["addArticle"]="Add a new article";
$GLOBALS['lgMap']["add"]="Add";
$GLOBALS['lgMap']["cancel"]="Cancel";
$GLOBALS['lgMap']["description"]="Description";
$GLOBALS['lgMap']["modify"]="Modify";
$GLOBALS['lgMap']["useThisPortal"]="Use this page";
$GLOBALS['lgMap']["addThisModuleInMyPage"]="Add this widget to my page";
$GLOBALS['lgMap']["modificationApplied"]="Your modifications have been applied!";
$GLOBALS['lgMap']["passwordModified"]="Your password has been modified!";
$GLOBALS['lgMap']["hello"]="Hi";
$GLOBALS['lgMap']["returnHome"]="Back to the Homepage";
$GLOBALS['lgMap']["missingModule"]="The widget is missing!";
$GLOBALS['lgMap']["addModAlreadyAccount"]="Have you already registered for a page in which you can add this widget?";
$GLOBALS['lgMap']["no"]="No";
$GLOBALS['lgMap']["yes"]="Yes";
$GLOBALS['lgMap']["addModuleOnPortal"]="Add this widget";
$GLOBALS['lgMap']["createPortalFromKw"]="Create a new portal from these tags";
$GLOBALS['lgMap']["exampleKw"]="example: APOD,Web 2.0,astronomy,stars...";
$GLOBALS['lgMap']["createMyPortal"]="Create this page";
$GLOBALS['lgMap']["email"]="Email";
$GLOBALS['lgMap']["yourEmail"]="Your email";
$GLOBALS['lgMap']["password"]="Password";
$GLOBALS['lgMap']["passwordMissing"]="Lost your password?";
$GLOBALS['lgMap']["passwordNotTyped"]="You haven't typed your password in!";
$GLOBALS['lgMap']["addTheModule"]="Add this widget";
$GLOBALS['lgMap']["yourAccount"]="Your portal";
$GLOBALS['lgMap']["addModSelectPage"]="Please select the page in which you want to add this widget";
$GLOBALS['lgMap']["yourArchivedArticles"]="Your articles have been saved";
$GLOBALS['lgMap']["startNavigatorOnCurrent"]="Start IE or Firefox on your portal";
$GLOBALS['lgMap']["modifyAccount"]="Modify my account";
$GLOBALS['lgMap']["disconnect"]="Logout";
$GLOBALS['lgMap']["yourAreRegistredNewsletter"]="You are now on the mailing list";
$GLOBALS['lgMap']["newsletterDesc"]="Please register for the newsletter to be advised about new widgets and functionalities";
$GLOBALS['lgMap']["ok"]="OK";
$GLOBALS['lgMap']["newsletterUnsuscribe"]="Unregister from the mailing list";
$GLOBALS['lgMap']["newsletterUnsubscribeBody"]="We have taken into account your demand to be unregistered from the mailing list";
$GLOBALS['lgMap']["yourRequestIsTreated"]="Your request has been treated";
$GLOBALS['lgMap']["valid"]="Validate";
$GLOBALS['lgMap']["emailSent"]="Email(s) sent!";
$GLOBALS['lgMap']["messageSent"]="Private message(s) sent!";
$GLOBALS['lgMap']["notMember"]="Please register for your free account!";
$GLOBALS['lgMap']["alreadyMember"]="You are already registered. If you have lost your password, please click on the 'Lost your password' link.";
$GLOBALS['lgMap']["incorrectLogin"]="Unknown user or incorrect password! Please try again.";
$GLOBALS['lgMap']["userNotValidated"]="User not validated. Please validate your account following the instructions recieved in your registration email!";
$GLOBALS['lgMap']["technicalIssue"]="Technical issue. Please try again later.";
$GLOBALS['lgMap']["remarkTakeInAccount"]="Your comment has been sent.";
$GLOBALS['lgMap']["yourRequest"]="Your request";
$GLOBALS['lgMap']["yourRequestBody"]="Hello\n\n\n\nI have taken your request: \n\n#1\n\n\n\n into account and will reply as soon as possible.\n\n\n\nThank You\n\n\n\n!";
$GLOBALS['lgMap']["erroneousEmail"]="Incorrect email!";
$GLOBALS['lgMap']["subscribeConfirmation"]="Subscription confirmation to ";
$GLOBALS['lgMap']["subscribeConfirmationBody"]="Hi\n\n\n\n you subscription has been taken into account. Please keep this email safely. Here is the information you entered: \n\n#1\n\n\n\nThis information will allow you to access to your account.\n\n\n\nSee you soon!";
$GLOBALS['lgMap']["invitesYouOnMsg"]=" invites you to try out this widget</A>.";
$GLOBALS['lgMap']["proposedSharing"]="Your page has been proposed to publication";
$GLOBALS['lgMap']["invitesYouOnPortalMsg"]=" invites you to use #1this page</A>";
$GLOBALS['lgMap']["sentBy"]="Sent by ";
$GLOBALS['lgMap']["yourModules"]="My widgets";
$GLOBALS['lgMap']["youHaveNoModVal"]="You don't have any active widget!";
$GLOBALS['lgMap']["youHaveXModVal"]="You have submitted #1 widget(s)";
$GLOBALS['lgMap']["youHaveNoModWait"]="You don't have any widget awaiting validation";
$GLOBALS['lgMap']["youHaveXModWait"]="You have #1 widget(s) awaiting validation";
$GLOBALS['lgMap']["createOrManageMods"]="Create / Manage your own widgets";
$GLOBALS['lgMap']["showPageWithModule"]="No, create an account";
$GLOBALS['lgMap']["connection"]="Login";
$GLOBALS['lgMap']["automaticConnection"]="Memorise";
$GLOBALS['lgMap']["yourActiveModules"]="Active widgets";
$GLOBALS['lgMap']["yourWaitingModules"]="Widgets awaiting validation";
$GLOBALS['lgMap']["createFromRssFeed"]="Create a widget from an existing RSS Feed";
$GLOBALS['lgMap']["youHaveJustCreatedThisModule"]="You have just created this widget. Please wait for its validation to use it and share it";
$GLOBALS['lgMap']["login"]="Username";
$GLOBALS['lgMap']["passwordMissingTxt"]="Lost your password?<BR />Just give us your email address and we will send a new password to the address you specified.";
$GLOBALS['lgMap']["passwordMissingBody"]="Hello\n\n\n\nYour password has been reset as requested. Here is your new password :\n\n#1\n\n\n\n\nSee you soon,\n\n\n\n.";
$GLOBALS['lgMap']["moduleTemporalyUnavailable"]="This widget is temporarily unavailable. We apologize for the inconvenience.";
$GLOBALS['lgMap']["moduleNotAvailableAnymore"]="This widget is no longer available in the widgets directory. You can delete this widget by clicking on the cross button. We apologize for the inconvenience.";
$GLOBALS['lgMap']["moddefEquivalentModules"]="Here is a list of widgets that could replace this one :";
$GLOBALS['lgMap']["pleaseConnectToYourPortals"]="Please login";
$GLOBALS['lgMap']["yourMessage"]="Your message";
$GLOBALS['lgMap']["by"]="By";
$GLOBALS['lgMap']["send"]="Send";
$GLOBALS['lgMap']["searchResultsFor"]="Search results for";
$GLOBALS['lgMap']["nextPage"]="Next page";
$GLOBALS['lgMap']["previousPage"]="Previous page";
$GLOBALS['lgMap']["modules"]="Widgets";
$GLOBALS['lgMap']["notebookUpdated"]="Your notebook has been updated !";
$GLOBALS['lgMap']["moduleInvitationTxt"]="Add the following widget to your pages";
$GLOBALS['lgMap']["lblMandatoryFields"]="The fields marked with the sign * are mandatory";
$GLOBALS['lgMap']["submit"]="Save";
$GLOBALS['lgMap']["hours"]="hour(s)";
$GLOBALS['lgMap']["pleaseTryLater"]="To reconnect, please try in";
$GLOBALS['lgMap']["tooManyTry"]="Too many failed connection tries";
$GLOBALS['lgMap']["confirmPassword"]="Confirm your password";
$GLOBALS['lgMap']["createNewRSS"]="Create a new RSS feed";
$GLOBALS['lgMap']["advancedSearch"]="Advanced search";
$GLOBALS['lgMap']["unsubscribeMessage"]="You have been unsubscribed";
$GLOBALS['lgMap']["fileTooBig"]="This file is too big";
$GLOBALS['lgMap']["extensionNotAllowed"]="This type of file is not allowed";
$GLOBALS['lgMap']["uploadNotSuccessful"]="The upload did not work";
$GLOBALS['lgMap']["nextStep"]="Next step";
$GLOBALS['lgMap']["accountUnsubscribe"]="To unsubscribe";
$GLOBALS['lgMap']["lblClickHere"]="Click here";
$GLOBALS['lgMap']["newCommentsOnNotebook"]="You've got new comments on your notebook";
$GLOBALS['lgMap']["commentsOnFollowingArticles"]="You've got new comments on the following articles :";

function lg(){
	$str=func_get_arg(0);
	$ret=(!empty($GLOBALS['lgMap'][$str]))?$GLOBALS['lgMap'][$str]:$str;
	for ($i=1;$i<func_num_args();$i++){$arg=func_get_arg($i);$ret=str_replace("#".$i,$arg,$ret);}
	return $ret;
}
?>
