<?php 
/* File generated by script since posh 2.0.2 */
$GLOBALS['lgMap']["myStatus"]="Meinen Status mitteilen (twittern)";
$GLOBALS['lgMap']["addGroup"]="Eine Gruppe hinzufügen";
$GLOBALS['lgMap']["Name"]="Name";
$GLOBALS['lgMap']["moduleInvitationTxt"]="Das folgende Modul zu eigenen Seite hinzufügen";
$GLOBALS['lgMap']["noArticle"]="Kein Artikel vorhanden";
$GLOBALS['lgMap']["portalInvitationTxt"]="Sie wurden eingeladen, diese Seite zu nutzen";
$GLOBALS['lgMap']["toReadOnOtherNotebooks"]="In den anderen Blogs ...";
$GLOBALS['lgMap']["addOnMyNotebook"]="Diesen Eintrag zu meinem Blog hinzufügen.";
$GLOBALS['lgMap']["openLinkedArticle"]="Offener verlinkter Artikel";
$GLOBALS['lgMap']["addNewPost"]="Einen neuen Artikel schreiben";
$GLOBALS['lgMap']["comments"]="Kommentar(e)";
$GLOBALS['lgMap']["trackbacks"]="Trackback(s)";
$GLOBALS['lgMap']["addNotebookToMyPage"]="Dieses Blog zu meinem Portal hinzufügen";
$GLOBALS['lgMap']["addAuthorInMyNetwork"]="Diesen Autor zu meinem Netzwerk hinzufügen";
$GLOBALS['lgMap']["theyTakeThisArticle"]="Folgende Personen zeigen diesen Artikel in ihrem Blog an";
$GLOBALS['lgMap']["options"]="Optionen";
$GLOBALS['lgMap']["licencedFor"]="Lizenz ausgestellt für:";
$GLOBALS['lgMap']["expireOn"]="Ablaufdatum";
$GLOBALS['lgMap']["changeKey"]="Den Schlüssel ändern";
$GLOBALS['lgMap']["enterClientNb"]="Kundennummer";
$GLOBALS['lgMap']["enterKey"]="Aktivierungsschlüssel";
$GLOBALS['lgMap']["networkArticle"]="Nur für mein Netzwerk";
$GLOBALS['lgMap']["privateArticle"]="Privater Artikel";
$GLOBALS['lgMap']["followCommentsRss"]="Folge den Kommentaren";
$GLOBALS['lgMap']["contactByEmail"]="Schicke dieser Person eine Mail";
$GLOBALS['lgMap']["GroupName"]="Gruppenbezeichnung";
$GLOBALS['lgMap']["addtoBook"]="Zu einem anderen Blog hinzufügen";
$GLOBALS['lgMap']["bestRegards"]="Mit freundlichen Grüßen";
$GLOBALS['lgMap']["getInMyNotebook"]="In eines meiner Blogs übernehmen";
$GLOBALS['lgMap']["groupNotifMessage"]="Hallo,\n\n#1 schickt Dir eine Einladung für die folgende Gruppe(n) : ";
$GLOBALS['lgMap']["groupNotifMessage2"]="\nUm diese Einladung zu akzeptieren, bitte hier #1 klicken.\nÖffnen Sie anschliessend die 'Netzwerk'-Seite und wählen Sie unter dem Link \"Meine Gruppen\" diejenige(n) aus, bei denen Sie Mitglied werden möchten. \n\nAb sofort können Sie dann mit den anderen Teilnehmern dieser Gruppe(n) Artikel und Kommentare austauschen.";
$GLOBALS['lgMap']["groupNotifSubject"]="Einladung einer Gruppe beizutreten";
$GLOBALS['lgMap']["NotebookGroup"]="Blog Gruppe";
$GLOBALS['lgMap']["notifEmailConfirmation"]="%site : wird ersetzt durch den Namen der Anwendung %link : wird ersetzt durch den Pfad der Anwendung (als Link)";
$GLOBALS['lgMap']["privateMemberArticle"]="Nur für Mitglieder";
$GLOBALS['lgMap']["selectBook"]="Ein Blog auswählen";
$GLOBALS['lgMap']["log"]="Logdateien";
$GLOBALS['lgMap']["lblFriendShareBtn5"]="Diesen Artikel anderen zur Verfügung stellen";

?>