/* File generated by script since posh 2.0.2 */
var lang=new Array;
lang["continue"]="Weiter";
lang["server"]="MySQL Server :<br />(Beispiel : localhost)";
lang["login"]="Zugang";
lang["password"]="Passwort";
lang["appname"]="Name der Webseite / des Portals";
lang["adminInterface"]="Administrationsbereich";
lang["menuPosition"]="Men&uuml;position";
lang["vertical"]="Links / Vertikal";
lang["horizontal"]="Unterhalb der Tabs / Horizontal";
lang["email"]="Email";
lang["installActiveCollabSuite"]="Installiere die Collaboration Suite (optional).";
lang["installActiveCollabSuiteDesc"]="Dieses Plugin installiert Funktionen die dann gemeinschaftlich genutzt werden können (Social Network, gemeinsames Journal für veröffentlichte Texte, Verwaltung von Gruppen(interessen), Suchmaschine, Chat, ....)";

var __lang='de';
function lg(v_s,v_p) {
	var l_ret=lang[v_s],indef;
	if(v_p && l_ret){l_ret=l_ret.replace("$$",v_p);}
	if (l_ret==indef)l_ret=v_s;
 	return l_ret;
}