<?php 
/* File generated by script since posh 2.0.2 */
$GLOBALS['lgMap']["addAuthorInMyNetwork"]="Legg til autorisatøren i mitt nettverk";
$GLOBALS['lgMap']["addGroup"]="Legg til en gruppe";
$GLOBALS['lgMap']["addNewPost"]="Skriv en ny artikkel.";
$GLOBALS['lgMap']["addNotebookToMyPage"]="Legg denne notatblokken til på min portal";
$GLOBALS['lgMap']["addOnMyNotebook"]="Legg det til på min notatblokk";
$GLOBALS['lgMap']["addtoBook"]="Leg til i en annen notatblokk.";
$GLOBALS['lgMap']["bestRegards"]="Vennligst hilsen, ";
$GLOBALS['lgMap']["changeKey"]="Endre nøkkelen.";
$GLOBALS['lgMap']["changePicture"]="Endre bilde. (.jpg format inntil 1MB)";
$GLOBALS['lgMap']["comments"]="Kommentarer.";
$GLOBALS['lgMap']["contactByEmail"]="Ta kontakt via epost.";
$GLOBALS['lgMap']["enterClientNb"]="Kundenummer";
$GLOBALS['lgMap']["enterKey"]="Aktiverings nøkkel";
$GLOBALS['lgMap']["expireOn"]="Utløps dato";
$GLOBALS['lgMap']["followCommentsRss"]="Følg kommentaren ";
$GLOBALS['lgMap']["getInMyNotebook"]="Hent inn til min notatblokk";
$GLOBALS['lgMap']["GroupName"]="Gruppenavn";
$GLOBALS['lgMap']["groupNotifMessage"]="Hei,\n\n#1 inviterer deg til følgende grupper :";
$GLOBALS['lgMap']["groupNotifMessage2"]="   \nTo akseptere denne invitasjonen, vennligst gå til #1 ,åpne 'nettverks' kategorien og klikk på 'bli med' for de respektive gruppene du ønsker å bli medlem av. Da vil du få muligheten til å publisere og lese artikler som hører til de gruppene du er medlem av.";
$GLOBALS['lgMap']["groupNotifSubject"]="Invitasjon i en gruppe.";
$GLOBALS['lgMap']["lblFriendShareBtn5"]="Del denne artikkelen ";
$GLOBALS['lgMap']["licencedFor"]="Lisensen er gitt til: ";
$GLOBALS['lgMap']["log"]="Logger ";
$GLOBALS['lgMap']["moduleInvitationTxt"]="Legg til følgende widget på din side";
$GLOBALS['lgMap']["myStatus"]="Min status";
$GLOBALS['lgMap']["Name"]="Navn";
$GLOBALS['lgMap']["networkArticle"]="Bare mitt nettverk";
$GLOBALS['lgMap']["noArticle"]="Ingen artikkel";
$GLOBALS['lgMap']["NotebookGroup"]="Notatblokk gruppe ";
$GLOBALS['lgMap']["notifEmailConfirmation"]="%site : Kommer til å bli byttet ut med applikasjonenes navn.\n\n%link : Kommer til å bli byttet ut med applikasjonenes kilde (som en lenke).";
$GLOBALS['lgMap']["openLinkedArticle"]="Åpne artikkelen det her linkes til.";
$GLOBALS['lgMap']["options"]="Alternativer";
$GLOBALS['lgMap']["portalInvitationTxt"]="Du har blitt invitert til å bruke denne siden";
$GLOBALS['lgMap']["privateArticle"]="Privat artikkel ";
$GLOBALS['lgMap']["privateMemberArticle"]="Kun for medlemmer ";
$GLOBALS['lgMap']["publicArticle"]="Offentlig artikkel ";
$GLOBALS['lgMap']["selectBook"]="Velg en notatblokk ";
$GLOBALS['lgMap']["theyTakeThisArticle"]="Artikkel som også vises på andre notatblokker";
$GLOBALS['lgMap']["toReadOnOtherNotebooks"]="I de andre notatblokkene ";
$GLOBALS['lgMap']["trackbacks"]="Tilbakefall";

?>