/* File generated by script since posh 2.0.2 */
var lang=new Array;
lang["adminInterface"]="Administrasjons grensesnitt.";
lang["appname"]="Navn på applikasjonen.";
lang["continue"]="FORTSETT";
lang["email"]="Epost";
lang["horizontal"]="under fanene/horisontalt ";
lang["installActiveCollabSuite"]="installer nettverks modulen (valgfritt)";
lang["installActiveCollabSuiteDesc"]="Dette programtillegget legger til nettsamfunns funksjoner i Posh. (sosilt nettverk, publiserings bøker, bestyring av temagrupper søkefunksjon chat, ....";
lang["login"]="Logg inn ";
lang["menuPosition"]="Meny posisjon ";
lang["password"]="Passord";
lang["server"]="MySQL server :\n\n(F.eks : localhost)";
lang["vertical"]="Lenker/vertikalt";

var __lang='no';
function lg(v_s,v_p) {
	var l_ret=lang[v_s],indef;
	if(v_p && l_ret){l_ret=l_ret.replace("$$",v_p);}
	if (l_ret==indef)l_ret=v_s;
 	return l_ret;
}