<?php 
/* File generated by script since posh 2.0.2 */
$GLOBALS['lgMap']["addAuthorInMyNetwork"]="เพิ่มผู้เขียนในเครือข่ายของฉัน";
$GLOBALS['lgMap']["addGroup"]="เพิ่มกลุ่ม";
$GLOBALS['lgMap']["addNewPost"]="เขียนบทความใหม่";
$GLOBALS['lgMap']["addNotebookToMyPage"]="เพิ่มสมุดโน้ตเข้าสู่พอร์ทัลของฉัน";
$GLOBALS['lgMap']["addOnMyNotebook"]="เพิ่มเข้าสู่สมุดโน้ต";
$GLOBALS['lgMap']["addtoBook"]="Add to another notebook";
$GLOBALS['lgMap']["bestRegards"]="Best regards,";
$GLOBALS['lgMap']["changeKey"]="Change the key";
$GLOBALS['lgMap']["changePicture"]="Change the picture (.jpg format, size <1MB)";
$GLOBALS['lgMap']["comments"]="Comment(s)";
$GLOBALS['lgMap']["contactByEmail"]="Contact by email";
$GLOBALS['lgMap']["enterClientNb"]="Customer number";
$GLOBALS['lgMap']["enterKey"]="Activation key";
$GLOBALS['lgMap']["expireOn"]="Expiration date";
$GLOBALS['lgMap']["followCommentsRss"]="Follow the comments";
$GLOBALS['lgMap']["getInMyNotebook"]="Copy to one of my notebooks";
$GLOBALS['lgMap']["GroupName"]="Group name";
$GLOBALS['lgMap']["groupNotifMessage"]="Hello,\n\n#1 invites you to the following groups : ";
$GLOBALS['lgMap']["groupNotifMessage2"]="\nTo accept this invitation, please go to #1 ,open the 'network' tab and in your groups, click 'join' for the groups you would like to join. You will be able then, to publish and read articles of the notebooks which belong to the groups you are a member of.";
$GLOBALS['lgMap']["groupNotifSubject"]="Invitation in a group";
$GLOBALS['lgMap']["licencedFor"]="Licence granted to";
$GLOBALS['lgMap']["log"]="logs";
$GLOBALS['lgMap']["moduleInvitationTxt"]="Add the following widget to your pages";
$GLOBALS['lgMap']["myStatus"]="My status";
$GLOBALS['lgMap']["Name"]="Name";
$GLOBALS['lgMap']["networkArticle"]="Only my network";
$GLOBALS['lgMap']["noArticle"]="No Article";
$GLOBALS['lgMap']["NotebookGroup"]="Notebook group";
$GLOBALS['lgMap']["notifEmailConfirmation"]="<b><font color='green'>%site</font> : </b>Will be replaced by the application name<br /><b><font color='green'>%link</font> : </b>Will be replaced by the application root (as a link)";
$GLOBALS['lgMap']["openLinkedArticle"]="Open linked article";
$GLOBALS['lgMap']["options"]="Options";
$GLOBALS['lgMap']["portalInvitationTxt"]="You have been invited to use this page";
$GLOBALS['lgMap']["privateArticle"]="Private article";
$GLOBALS['lgMap']["privateMemberArticle"]="Reserved to members";
$GLOBALS['lgMap']["publicArticle"]="Public article";
$GLOBALS['lgMap']["selectBook"]="Select notebook";
$GLOBALS['lgMap']["theyTakeThisArticle"]="Article shows also on other notebooks";
$GLOBALS['lgMap']["toReadOnOtherNotebooks"]="In the other notebooks ...";
$GLOBALS['lgMap']["trackbacks"]="Trackback(s)";
$GLOBALS['lgMap']["lblFriendShareBtn5"]="Share this article";

?>